- name: Add JRE ppa
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main"

- name: fix key
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install JRE
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes
